# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ao91J7F_TQPoG7vqW_89pHZpif2THUIA
"""

import math
import os
import random
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple


import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import yfinance as yf
from tqdm import tqdm
import matplotlib.pyplot as plt


# ----------------------------
# Configuration
# ----------------------------
CONFIG = {
"ticker": "AAPL",
"start": "2015-01-01",
"end": "2024-12-31",
"interval": "1d",
"target_col": "Close",
"features": ["Open", "High", "Low", "Close", "Volume"],
# window: how many past steps to use; horizon: how many future steps to forecast
"window": 90,
"horizon": 7,
"batch_size": 64,
"transformer": {
"d_model": 128,
"nhead": 8,
"num_encoder_layers": 3,
"num_decoder_layers": 2,
"dim_feedforward": 256,
"dropout": 0.1,
},
"lstm": {"hidden_size": 128, "num_layers": 2, "dropout": 0.1},
"training": {
"epochs": 60,
"lr": 1e-4,
"weight_decay": 1e-5,
"patience": 8,
"device": "cuda" if torch.cuda.is_available() else "cpu",
},
"seed": 42,
"save_dir": "./checkpoints",
}